FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

ARG http_proxy=http://202.38.69.70:3129
ARG https_proxy=http://202.38.69.70:3129

RUN apt update; DEBIAN_FRONTEND=noninteractive apt install -y tzdata openssh-server rsync vim git unrar zip p7zip-full && \
apt autoclean && apt autoremove

ENV TZ=Asia/Shanghai

RUN which pip && pip config set global.trusted-host mirrors.aliyun.com && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --upgrade pip --no-cache-dir && \
    pip install flash-attn --no-build-isolation --no-cache-dir && \
    pip install timm einops kornia --no-cache-dir && \
    pip install matplotlib scikit-learn --no-cache-dir && \
    pip install bitsandbytes --no-cache-dir && \
    pip install diffusers[torch] transformers==4.51.3 accelerate datasets --no-cache-dir && \
    pip install deepspeed --no-cache-dir && \
    pip install pyiqa --no-cache-dir && \
    pip install transformers -U --no-cache-dir && \
    pip install tensorboard wandb --no-cache-dir && \
    pip install gdown lmdb --no-cache-dir && \
    pip install pandas scikit-image imageio imagecodecs scipy==1.14.1 --no-cache-dir && \
    pip install omegaconf --no-cache-dir && \
    pip install python-dotenv icecream --no-cache-dir && \
    pip install loralib peft --no-cache-dir && \
    pip install rawpy==0.21.0 fairscale --no-cache-dir && \
    pip uninstall -y opencv-python --no-cache-dir && \
    pip uninstall -y opencv-python-headless --no-cache-dir && \
    pip install opencv-python-headless --no-cache-dir && \
    conda clean --all -y

# Add a user
RUN useradd -m lx -u 1021 -s /bin/bash && \
    echo "lx:122408" | chpasswd && \
    echo "lx ALL=(ALL) ALL" >> /etc/sudoers

USER lx
WORKDIR /home/lx
