FROM do.nark.eu.org/pytorch/pytorch:2.3.0-cuda11.8-cudnn8-devel

ENV NV_CUDA_COMPAT_PACKAGE=
ENV NVIDIA_REQUIRE_CUDA=
ENV NV_CUDA_CUDART_VERSION=
ENV CUDA_VERSION=
# ENV TORCH_CUDA_ARCH_LIST="6.1 7.0 7.2 7.5 8.0 8.6"
ENV TCNN_CUDA_ARCHITECTURES="61,70,72,75,80,86"
RUN rm /usr/local/cuda-11.8/compat -rfv
RUN apt update; DEBIAN_FRONTEND=noninteractive apt install -y tzdata openssh-server rsync vim git unrar p7zip-full && \
apt autoclean && apt autoremove

ENV TZ=Asia/Shanghai

RUN which pip && pip config set global.trusted-host mirrors.aliyun.com && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --upgrade pip --no-cache-dir && \
    pip install git+https://gitee.com/zml615/tiny-cuda-nn.git#subdirectory=bindings/torch --no-cache-dir && \
    conda clean --all -y

# Add a user
RUN useradd -m zhangml -u 1962 -s /bin/bash && \
    echo "zhangml:123456" | chpasswd && \
    echo "zhangml ALL=(ALL) ALL" >> /etc/sudoers

USER zhangml
WORKDIR /home/zhangml