# FROM pytorch/pytorch:2.4.1-cuda12.1-cudnn9-devel
FROM docker.1ms.run/pytorch/pytorch:2.4.1-cuda12.1-cudnn9-devel

ARG http_proxy=http://202.38.69.70:3129
ARG https_proxy=http://202.38.69.70:3129

RUN apt update; DEBIAN_FRONTEND=noninteractive apt install -y tzdata openssh-server rsync vim git unrar p7zip-full && \
apt autoclean && apt autoremove

ENV TZ=Asia/Shanghai

RUN which pip && pip config set global.trusted-host mirrors.aliyun.com && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --upgrade pip --no-cache-dir && \
    pip install xformers==0.0.28 --index-url https://mirror.sjtu.edu.cn/pytorch-wheels/cu121 --no-cache-dir && \
    pip install timm einops kornia --no-cache-dir && \
    pip install matplotlib scikit-learn --no-cache-dir && \
    pip install bitsandbytes --no-cache-dir && \
    pip install diffusers[torch] transformers accelerate datasets --no-cache-dir && \
    pip install deepspeed --no-cache-dir && \
    pip install pyiqa --no-cache-dir && \
    pip install transformers -U --no-cache-dir && \
    pip install tensorboard wandb --no-cache-dir && \
    pip install gdown lmdb --no-cache-dir && \
    pip install pandas scikit-image imageio imagecodecs scipy==1.14.1 --no-cache-dir && \
    pip install omegaconf --no-cache-dir && \
    pip install python-dotenv icecream --no-cache-dir && \
    pip install loralib peft --no-cache-dir && \
    pip install rawpy==0.21.0 fairscale --no-cache-dir && \
    pip uninstall -y opencv-python --no-cache-dir && \
    pip uninstall -y opencv-python-headless --no-cache-dir && \
    pip install opencv-python-headless --no-cache-dir && \
    # pip install natten==0.17.3+torch240cu121 -f https://shi-labs.com/natten/wheels/ --no-cache-dir && \
    # pip install pandas yapf scikit-image future addict tomli lazy_loader PyWavelets imageio --no-cache-dir && \
    conda clean --all -y

COPY "natten-0.17.3+torch240cu121-cp311-cp311-linux_x86_64.whl" /tmp/
RUN pip install /tmp/natten-0.17.3+torch240cu121-cp311-cp311-linux_x86_64.whl --no-cache-dir && \
    rm -rf /tmp/natten-0.17.3+torch240cu121-cp311-cp311-linux_x86_64.whl

# Add a user
RUN useradd -m lx -u 1021 -s /bin/bash && \
    echo "lx:122408" | chpasswd && \
    echo "lx ALL=(ALL) ALL" >> /etc/sudoers

USER lx
WORKDIR /home/lx
