FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

ENV NV_CUDA_COMPAT_PACKAGE=
ENV NVIDIA_REQUIRE_CUDA=
ENV NV_CUDA_CUDART_VERSION=
ENV CUDA_VERSION=
RUN rm /usr/local/cuda-12.4/compat -rfv
RUN apt update; DEBIAN_FRONTEND=noninteractive apt install -y tzdata openssh-server rsync vim git unrar p7zip-full && \
apt autoclean && apt autoremove

ENV TZ=Asia/Shanghai

RUN which pip && pip config set global.trusted-host mirrors.aliyun.com && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --upgrade pip wheel setuptools --no-cache-dir && \
    pip install flash-attn --no-build-isolation --no-cache-dir && \
    pip install timm einops kornia --no-cache-dir && \
    pip install matplotlib scikit-learn --no-cache-dir && \
    pip install bitsandbytes --no-cache-dir && \
    pip install diffusers[torch] transformers==4.51.3 accelerate datasets --no-cache-dir && \
    pip install deepspeed --no-cache-dir && \
    pip install pyiqa --no-cache-dir && \
    pip install tensorboard wandb --no-cache-dir && \
    pip install gdown lmdb --no-cache-dir && \
    pip install pandas scikit-image imageio imagecodecs scipy==1.14.1 --no-cache-dir && \
    pip install omegaconf --no-cache-dir && \
    pip install python-dotenv icecream --no-cache-dir && \
    pip install loralib peft --no-cache-dir && \
    pip install rawpy==0.21.0 fairscale --no-cache-dir && \
    pip uninstall -y opencv-python --no-cache-dir && \
    pip uninstall -y opencv-python-headless --no-cache-dir && \
    pip install opencv-python-headless --no-cache-dir && \
    # pip install pandas yapf scikit-image future addict tomli lazy_loader PyWavelets imageio --no-cache-dir && \
    conda clean --all -y

# Add a user
RUN useradd -m luoxin -u 1647 -s /bin/bash && \
    echo "luoxin:122408" | chpasswd && \
    echo "luoxin ALL=(ALL) ALL" >> /etc/sudoers

USER luoxin
WORKDIR /home/luoxin
