FROM do.nark.eu.org/pytorch/pytorch:2.3.0-cuda11.8-cudnn8-devel

ENV NV_CUDA_COMPAT_PACKAGE=
ENV NVIDIA_REQUIRE_CUDA=
ENV NV_CUDA_CUDART_VERSION=
ENV CUDA_VERSION=
RUN rm /usr/local/cuda-11.8/compat -rfv
RUN apt update; DEBIAN_FRONTEND=noninteractive apt install -y tzdata openssh-server rsync vim git unrar p7zip-full && \
apt autoclean && apt autoremove

ENV TZ=Asia/Shanghai

RUN which pip && pip config set global.trusted-host mirrors.aliyun.com && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --upgrade pip --no-cache-dir && \
    pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch --no-cache-dir && \
    conda clean --all -y